_old/app/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :subscribers
  resources :subscriptions

  get 'accounts', to: 'accounts#index'
  post 'accounts', to: 'accounts#create'
  post 'messages/incoming', to: 'messages#incoming'
  post 'quicksend', to: 'messages#quicksend_create'

  get 'm/:phone_hash/:manage_token', to: 'subscribers#manage'

  resources :accounts, only: [:show, :new, :edit, :create, :update, :destroy], path: 'a' do
    get 'quicksend', to: 'messages#new'
    post 'quicksend', to: 'messages#quicksend_create'

    resources :lists
    resources :conversations, only: [:index, :show]
    resources :campaigns do
      post 'send_it', on: :collection
    end
  end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" }
  else
    devise_for :users
  end

  resources :users
  resources :roles

  root to: 'accounts#index'
  post '/md5', to: 'application#generate_md5'
  get '/md5', to: 'application#generate_md5'
end

_old/app/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :subscriber
  belongs_to :list
  belongs_to :account
end

_old/app/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :phone_number, :email, :description, :subscriber_id, :list_id, :account_id, :status)
    end
end

_old/app/app/helpers/reports_helper.rb
module ReportsHelper
end

_old/app/app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :subscriber_id %><br>
    <%= f.text_field :subscriber_id %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.text_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

_old/app/app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

_old/app/app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Description</th>
      <th>Subscriber</th>
      <th>List</th>
      <th>Account</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= report.phone_number %></td>
        <td><%= report.email %></td>
        <td><%= report.description %></td>
        <td><%= report.subscriber %></td>
        <td><%= report.list %></td>
        <td><%= report.account %></td>
        <td><%= report.status %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

_old/app/app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

_old/app/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @report.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @report.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Subscriber:</strong>
  <%= @report.subscriber %>
</p>

<p>
  <strong>List:</strong>
  <%= @report.list %>
</p>

<p>
  <strong>Account:</strong>
  <%= @report.account %>
</p>

<p>
  <strong>Status:</strong>
  <%= @report.status %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>