_old/app/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :subscribers
  resources :subscriptions

  get 'accounts', to: 'accounts#index'
  post 'accounts', to: 'accounts#create'
  post 'messages/incoming', to: 'messages#incoming'
  post 'quicksend', to: 'messages#quicksend_create'

  get 'm/:phone_hash/:manage_token', to: 'subscribers#manage'

  resources :accounts, only: [:show, :new, :edit, :create, :update, :destroy], path: 'a' do
    get 'quicksend', to: 'messages#new'
    post 'quicksend', to: 'messages#quicksend_create'

    resources :lists
    resources :conversations, only: [:index, :show]
    resources :campaigns do
      post 'send_it', on: :collection
    end
  end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" }
  else
    devise_for :users
  end

  resources :users
  resources :roles

  root to: 'accounts#index'
  post '/md5', to: 'application#generate_md5'
  get '/md5', to: 'application#generate_md5'
end

_old/app/app/models/list.rb
class List < ActiveRecord::Base
  resourcify

  belongs_to :account
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions
  
  validates :name, presence: true
  validates :account_id, presence: true
end

_old/app/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  before_action :set_account

  def index
    @lists = @account.lists
  end

  def show
    @subscribers = @list.subscribers
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    @list.account_id = @account.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to account_list_path(@account, @list), notice: 'List was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to account_list_path(@account, @list), notice: 'List was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to account_lists_url(@account), notice: 'List was successfully destroyed.' }
    end
  end

  private
    def set_account
      @account = Account.find(params[:account_id])
    end

    def list_params
      params.require(:list).permit(:name, :description)
    end
end

_old/app/app/helpers/lists_helper.rb
module ListsHelper
end

_old/app/app/views/lists/_form.html.erb
<%= form_for([@account, @list], html: {class: 'ui form'}) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <strong><%= f.label :name %></strong>
  <%= f.text_field :name, placeholder: "name" %>
  <br><br>
  <strong><%= f.label :description %></strong>
  <%= f.text_area :description, placeholder: "Description" %>

  <br><br>
  <%= f.submit class: "ui button fluid primary" %>
<% end %>

_old/app/app/views/lists/edit.html.erb
<% content_for :title, "#{ @account.name } > Lists > #{ @list.name }" %>

<div class="ui container">
  <div class="ui three column centered grid">
    <div class="column">
      <div class="ui segment">
        <h1>Editing List</h1>

        <%= render 'form' %>

        <%= link_to 'Show', account_list_path(@account, @list), class: "ui button" %>&nbsp;
        <%= link_to 'Back', account_lists_path(@account), class: "ui button basic" %>
      </div>
    </div>
  </div>

</div>

_old/app/app/views/lists/index.html.erb
<div class="c-wrapper-content c-wrapper-content--clean">
  <div class="c-header">
    <h1 class='c-header__title'>Lists</h1>
    <%= link_to 'New List', new_account_list_path(@account), class: "ui button primary c-header__cta" %>
    </div>

  <div class='c-body'>
    <div class='c-body__inner'>
      <div class="ui one column centered grid">
        <div class="column">

          <table class="ui very basic collapsing padded celled table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @lists.each do |list| %>
                <tr>
                  <td><%= list.name %></td>
                  <td><%= list.description %></td>
                  <td><%= link_to 'Show', account_list_path(@account, list) %></td>
                  <td><%= link_to 'Edit', edit_account_list_path(@account, list) %></td>
                  <td><%= link_to 'Destroy', account_list_path(@account, list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

_old/app/app/views/lists/new.html.erb
<% content_for :title, "#{@account.name} > Lists > New" %>

<div class="c-wrapper-content">
  <div class="ui three column centered grid">
    <div class="column">
      <div class="ui segment">
        <h1>New List</h1>

        <%= render 'form' %>

      </div>
      <%= link_to 'Back', account_lists_path(@account), class: "ui button fluid basic" %>

    </div>
  </div>
</div>

_old/app/app/views/lists/show.html.erb
<% content_for :title, "#{ @account.name } > Lists > #{ @list.name }" %>

<div class="c-wrapper-content">
  <div class="ui centered grid">
    <div class="six wide column">
      <div class="ui segment center">
        <h1>Lists > <%= @list.name %></h1>
        <br>
        <%= @list.description %>
      </div>
      <div class="ui buttons fluid">
        <%= link_to 'Edit', edit_account_list_path(@account, @list), class: 'ui button primary' %>
        <%= link_to 'Back', account_lists_path(@account), class: 'ui button' %>
      </div>
    </div>
    <div class="ten wide column">
      <div class="ui divided list">
        <% @subscribers.each do |s| %>
          <div class="item">
            <strong><%# s.phone_number %></strong>
            &nbsp;&mdash;&nbsp;
            <%= s.name %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>