_old/app/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :subscribers
  resources :subscriptions

  get 'accounts', to: 'accounts#index'
  post 'accounts', to: 'accounts#create'
  post 'messages/incoming', to: 'messages#incoming'
  post 'quicksend', to: 'messages#quicksend_create'

  get 'm/:phone_hash/:manage_token', to: 'subscribers#manage'

  resources :accounts, only: [:show, :new, :edit, :create, :update, :destroy], path: 'a' do
    get 'quicksend', to: 'messages#new'
    post 'quicksend', to: 'messages#quicksend_create'

    resources :lists
    resources :conversations, only: [:index, :show]
    resources :campaigns do
      post 'send_it', on: :collection
    end
  end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" }
  else
    devise_for :users
  end

  resources :users
  resources :roles

  root to: 'accounts#index'
  post '/md5', to: 'application#generate_md5'
  get '/md5', to: 'application#generate_md5'
end

_old/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> - Pushly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="c-nav-top">
    <div class="c-nav-top-one">
      <% if user_signed_in? %>
        <div class="c-navone__add js-navone__add ">
        </div>
        <!-- <div class="c-navone__add js-navone__add ui dropdown">
          <div class="text"><i class="icon plus"></i></div>
          <i class="dropdown icon"></i>
          <div class="menu">
            <div class="header">Create a New</div>
            <div class="divider"></div>
            <%= link_to "Account", new_account_path, class: 'item' %>
            <% if @account && @account.id != nil%>
              <%= link_to "List", new_account_list_path(@account), class: 'item' %>
              <%= link_to "Campaign", new_account_campaign_path(@account), class: 'item' %>
            <% end %>
          </div>
        </div> -->
      <% end %>
      <div class="c-navone__logo">
        <%= image_tag('logos/horz.svg') %>
      </div>
      <% if user_signed_in? %>
        <div class="c-navone__user js-navone__user ui dropdown">
          <!-- <div class="text"><%= current_user.name %></div>
          <i class="dropdown icon"></i>
          <div class="menu _menu--right">
            <%= link_to "Profile Settings", edit_user_registration_path(current_user), class: 'item' %>
            <div class="item">Billing (Coming Soon)</div>
            <div class="divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'item' %>
          </div> -->
        </div>
      <% else %>
        <div class="c-navone__user js-navone__user">
          <%= link_to "Sign In", new_user_session_path, class: 'ui button basic' %>
          &nbsp;&nbsp;&nbsp;
          <%= link_to "Sign Up", new_user_registration_path, class: 'ui button' %>
        </div>
      <% end %>
    </div>

    <!-- <div class="c-nav-top-two">
      <h3><%= yield :title %></h3>
    </div> -->
  </div>

  <div class="c-nav-left">
    <% if user_signed_in? %>
      <div class="c-nav-left__profile">
        <%= gravatar(current_user.email) %>
        <div class="name"><%= current_user.name %></div>
        <div class="phone"><%= current_user.phone_number %></div>
      </div>
      <ul class="c-nav-left__menu">
        <% if @account && @account.id != nil%>
          <span class="label"><%= @account.name %></span>
          <%= nav_link "Dashboard", "dashboard", @account %>
          <%= nav_link "Conversations", "comments", account_conversations_path(@account) %>
          <%= nav_link "Campaigns", "comment", account_campaigns_path(@account) %>
          <%= nav_link "Lists", "sidebar", account_lists_path(@account) %>
        <% elsif current_user.accounts != nil %>
          <span class="label">Select An Account</span>
          <% current_user.accounts.each do |a| %>
            <%= nav_link a.name, "", account_path(a) %>
          <% end %>
          <%= nav_link "New Account", "plus", new_account_path %>
        <% else %>
          <%= nav_link "New Account", "plus", new_account_path %>
        <% end %>
      </ul>

      <ul class="c-nav-left__footer">
        <%= nav_link "", "setting", edit_user_registration_path %>
        <li><%= link_to "<i class='sign out icon'></i>".html_safe, destroy_user_session_path, method: :delete %></li>
      </ul>
    <% end %>
  </div>

  <div class="c-wrapper">
    <% if flash[:notice] %>
      <div class="ui message fadeout floating primary c-alert">
        <i class="close icon"></i>
        <div class="header"><%= flash[:notice] %></div>
      </div>
    <% end %>
      <%= yield %>
  </div>

</body>
</html>

_old/app/app/views/layouts/select.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pushly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="c-select">
  <div class="ui container">
    <div class="ui two column centered grid">
      <div class="column">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>