_old/app/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :subscribers
  resources :subscriptions

  get 'accounts', to: 'accounts#index'
  post 'accounts', to: 'accounts#create'
  post 'messages/incoming', to: 'messages#incoming'
  post 'quicksend', to: 'messages#quicksend_create'

  get 'm/:phone_hash/:manage_token', to: 'subscribers#manage'

  resources :accounts, only: [:show, :new, :edit, :create, :update, :destroy], path: 'a' do
    get 'quicksend', to: 'messages#new'
    post 'quicksend', to: 'messages#quicksend_create'

    resources :lists
    resources :conversations, only: [:index, :show]
    resources :campaigns do
      post 'send_it', on: :collection
    end
  end

  if Rails.env.production?
    devise_for :users, :controllers => { :registrations => "registrations" }
  else
    devise_for :users
  end

  resources :users
  resources :roles

  root to: 'accounts#index'
  post '/md5', to: 'application#generate_md5'
  get '/md5', to: 'application#generate_md5'
end

_old/app/app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_many :subscriptions
  has_many :lists, through: :subscriptions
  has_many :converastions

  validates :phone_number, presence: true, uniqueness: true

  after_create :generate_phone_number_hashed

  def send_account_blocked_message
    @subscriber = self
    @pushly = Account.where(sid: ENV['PUSHLY_SID'])

    Message.create({
      sent_by: "account",
      from: @pushly.phone_number,
      to: @subscriber.phone_number,
      account_id: @pushly.id,
      subscriber_id: @subscriber.id,
      text: "Your phone number is currently blocked from interacting with Pushly businesses. Want to re-enable it? Email us: hello@pushly.co"
    })
  end

  def generate_manage_token
    self.manage_token_created_at = Time.now
    self.manage_token = SecureRandom.urlsafe_base64(64)
    self.save!
    return self.manage_token
  end

  def check_manage_token(token_attempt)
    if Time.now <= self.manage_token_created_at + 1.hour && self.manage_token === token_attempt
      true
    else
      false
    end
  end

  def generate_manage_link
    phone_hash = self.phone_number_hashed
    manage_token = self.generate_manage_token
    url = 'http://localhost:3000' + '/m/' + phone_hash + '/' + manage_token

    return url
  end

  def send_manage_text
  end

  def send_info_text
  end

  def send_sub_text
  end

  def send_unsub_text
  end

  protected

  def generate_phone_number_hashed
    self.phone_number_hashed = Digest::MD5.hexdigest(self.phone_number)
    self.save!
  end

  # def engage_with_subscriber
  #   @client = Twilio::REST::Client.new
  #
  #   @client.account.messages.create({
  #     :from => Account.first.phone_number,
  #     :to => self.phone_number,
  #     :body => 'Welcome! What\'s your name?',
  #   })
  # end
end

_old/app/app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # load_and_authorize_resource
  before_filter :authenticate_user!, except: [:manage]
  before_filter :find_by_hash, only: [:manage]

  def index
    @subscribers = Subscriber.all
  end

  def show
    @subscriber = Subscriber.find(params[:id])
    @subscription = @subscriber.subscriptions.build
  end

  def manage
    if @subscriber.check_manage_token(params[:manage_token])
      @subscriptions = @subscriber.subscriptions
    else
      redirect_to root_url, notice: 'This is not a valid link. It may have expired. Try texting MANAGE again. :)'
    end
  end

  def new
    @subscriber = Subscriber.new
  end

  def edit
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
    end
  end

  private
    def find_by_hash
      @subscriber = Subscriber.where(phone_number_hashed: params[:phone_hash]).limit(1).first
    end

    def subscriber_params
      params.require(:subscriber).permit(:name, :bio, :phone_number, :phone_number_hashed, :manage_token)
    end
end

_old/app/app/helpers/subscribers_helper.rb
module SubscribersHelper
end

_old/app/app/views/subscribers/_form.html.erb
<%= form_for @subscriber, html: {class: 'ui form'} do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

_old/app/app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

_old/app/app/views/subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Phone number</th>
      <th>Uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.bio %></td>
        <td><%# subscriber.phone_number %></td>
        <td><%= subscriber.uuid %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

_old/app/app/views/subscribers/manage.html.erb
<h1>Editing Subscriber</h1>

<h2><%= @subscriber.name %></h2>
<h4><%= @subscriber.phone_number %></h4>

_old/app/app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

_old/app/app/views/subscribers/show.html.erb
<div class="c-wrapper-content">
  <div class="ui one column centered grid">
    <div class="column">
      <div class="ui segment center">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @subscriber.name %>
        </p>

        <p>
          <strong>Bio:</strong>
          <%= @subscriber.bio %>
        </p>

        <p>
          <strong>Phone number:</strong>
          <%= @subscriber.phone_number %>
        </p>

        <p>
          <strong>Uuid:</strong>
          <%= @subscriber.uuid %>
        </p>

        <p>
          <strong>Subscriptions:</strong>
          <fieldset>
            <% @subscriber.lists.each do |l| %>
              <div>- <%= l.name %> (<%= l.account.name %> <em>by <%= l.account.user.name %></em>)</div>
            <% end %>
          </fieldset>
        </p>

          <%= form_for @subscription do |s_new| %>
            <%= s_new.hidden_field :subscriber_id, value: @subscriber.id %>
            <%= s_new.collection_select(:list_id, List.all, :id, :name, prompt: true) %>
            <%= s_new.submit %>
          <% end %>

        <%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
        <%= link_to 'Back', subscribers_path %>
      </div>
    </div>
  </div>
</div>